"""add cancelled status

Revision ID: 310ffe978c69
Revises: b3eeab5ebde9
Create Date: 2026-06-19 15:29:33.266811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310ffe978c69'
down_revision: Union[str, Sequence[str], None] = 'b3eeab5ebde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE booking_status  ADD VALUE 'cancelled'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
